#this file is common  and shared between development and production
version: '3'
services:
  node-app:
    image: aake99/node-app-image
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    # development - producation  
    env_file:
      - ./.env
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root

  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  # create volumes according to documantaion for mongo     
volumes:
  postgres-db:

  #mongo:
   #image: mongo
    #restart: always
    # to save db in hard desc instead of memory
    #volumes:
     # - mongo-db:/data/db
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
  #mongo-express:
    #image: mongo-express
    #restart: always
    #depends_on:
     # - mongo
    #ports:
     # - 8081:8081
    #environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #3ME_CONFIG_MONGODB_ADMINPASSWORD: example
           # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
